project11/platforms/bob:
  robot_description: bob/robot_description
  width: 1.7
  length: 4.25
  reference_x: 0.525
  nav_sources:
    combined:
      position_topic: /bob/project11/nav/position
      orientation_topic: /bob/project11/nav/orientation
      velocity_topic: /bob/project11/nav/velocity